# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogs/preferences.ui'
#
# Created: Wed Dec  3 21:08:34 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Preferences(object):
    def setupUi(self, Preferences):
        Preferences.setObjectName("Preferences")
        Preferences.resize(465, 374)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Preferences.sizePolicy().hasHeightForWidth())
        Preferences.setSizePolicy(sizePolicy)
        self.vertical_layout = QtWidgets.QVBoxLayout(Preferences)
        self.vertical_layout.setObjectName("vertical_layout")
        self.tab_widget = QtWidgets.QTabWidget(Preferences)
        self.tab_widget.setObjectName("tab_widget")
        self.interface_tab = QtWidgets.QWidget()
        self.interface_tab.setObjectName("interface_tab")
        self.vertical_layout_4 = QtWidgets.QVBoxLayout(self.interface_tab)
        self.vertical_layout_4.setObjectName("vertical_layout_4")
        self.form_layout = QtWidgets.QFormLayout()
        self.form_layout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.form_layout.setObjectName("form_layout")
        self.default_tool_label = QtWidgets.QLabel(self.interface_tab)
        self.default_tool_label.setObjectName("default_tool_label")
        self.form_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.default_tool_label)
        self.default_tool_combo_box = QtWidgets.QComboBox(self.interface_tab)
        self.default_tool_combo_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.default_tool_combo_box.setProperty("current_index", 0)
        self.default_tool_combo_box.setObjectName("default_tool_combo_box")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pathtools/dlg_select"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.default_tool_combo_box.addItem(icon, "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pathtools/dlg_pencil"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.default_tool_combo_box.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pathtools/dlg_paint"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.default_tool_combo_box.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/pathtools/dlg_addseq"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.default_tool_combo_box.addItem(icon3, "")
        self.form_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.default_tool_combo_box)
        self.zoom_speed_label = QtWidgets.QLabel(self.interface_tab)
        self.zoom_speed_label.setObjectName("zoom_speed_label")
        self.form_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.zoom_speed_label)
        self.zoom_speed_slider = QtWidgets.QSlider(self.interface_tab)
        self.zoom_speed_slider.setMinimumSize(QtCore.QSize(140, 0))
        self.zoom_speed_slider.setMinimum(1)
        self.zoom_speed_slider.setMaximum(100)
        self.zoom_speed_slider.setSingleStep(1)
        self.zoom_speed_slider.setProperty("value", 50)
        self.zoom_speed_slider.setOrientation(QtCore.Qt.Horizontal)
        self.zoom_speed_slider.setInvertedControls(False)
        self.zoom_speed_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.zoom_speed_slider.setTickInterval(0)
        self.zoom_speed_slider.setObjectName("zoom_speed_slider")
        self.form_layout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.zoom_speed_slider)
        self.show_icon_label_text = QtWidgets.QLabel(self.interface_tab)
        self.show_icon_label_text.setObjectName("show_icon_label_text")
        self.form_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.show_icon_label_text)
        self.show_icon_labels = QtWidgets.QCheckBox(self.interface_tab)
        self.show_icon_labels.setText("")
        self.show_icon_labels.setChecked(True)
        self.show_icon_labels.setObjectName("show_icon_labels")
        self.form_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.show_icon_labels)
        self.vertical_layout_4.addLayout(self.form_layout)
        self.button_box = QtWidgets.QDialogButtonBox(self.interface_tab)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.RestoreDefaults)
        self.button_box.setObjectName("button_box")
        self.vertical_layout_4.addWidget(self.button_box)
        self.tab_widget.addTab(self.interface_tab, "")
        self.parts_tab = QtWidgets.QWidget()
        self.parts_tab.setObjectName("parts_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.parts_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_widget_2 = QtWidgets.QTabWidget(self.parts_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_widget_2.sizePolicy().hasHeightForWidth())
        self.tab_widget_2.setSizePolicy(sizePolicy)
        self.tab_widget_2.setObjectName("tab_widget_2")
        self.tab_honeycomb = QtWidgets.QWidget()
        self.tab_honeycomb.setObjectName("tab_honeycomb")
        self.vertical_layout_3 = QtWidgets.QVBoxLayout(self.tab_honeycomb)
        self.vertical_layout_3.setObjectName("vertical_layout_3")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.dimensionsLabel1 = QtWidgets.QLabel(self.tab_honeycomb)
        self.dimensionsLabel1.setObjectName("dimensionsLabel1")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dimensionsLabel1)
        self.honeycomb_g_layout = QtWidgets.QGridLayout()
        self.honeycomb_g_layout.setContentsMargins(-1, 3, -1, -1)
        self.honeycomb_g_layout.setObjectName("honeycomb_g_layout")
        self.honeycomb_rows_spin_box = QtWidgets.QSpinBox(self.tab_honeycomb)
        self.honeycomb_rows_spin_box.setMinimum(6)
        self.honeycomb_rows_spin_box.setMaximum(200)
        self.honeycomb_rows_spin_box.setProperty("value", 30)
        self.honeycomb_rows_spin_box.setObjectName("honeycomb_rows_spin_box")
        self.honeycomb_g_layout.addWidget(self.honeycomb_rows_spin_box, 0, 0, 1, 1)
        self.honeycomb_cols_spin_box = QtWidgets.QSpinBox(self.tab_honeycomb)
        self.honeycomb_cols_spin_box.setMinimum(6)
        self.honeycomb_cols_spin_box.setMaximum(200)
        self.honeycomb_cols_spin_box.setProperty("value", 32)
        self.honeycomb_cols_spin_box.setObjectName("honeycomb_cols_spin_box")
        self.honeycomb_g_layout.addWidget(self.honeycomb_cols_spin_box, 0, 1, 1, 1)
        self.h_rows_label = QtWidgets.QLabel(self.tab_honeycomb)
        self.h_rows_label.setAlignment(QtCore.Qt.AlignCenter)
        self.h_rows_label.setObjectName("h_rows_label")
        self.honeycomb_g_layout.addWidget(self.h_rows_label, 1, 0, 1, 1)
        self.h_cols_label = QtWidgets.QLabel(self.tab_honeycomb)
        self.h_cols_label.setAlignment(QtCore.Qt.AlignCenter)
        self.h_cols_label.setObjectName("h_cols_label")
        self.honeycomb_g_layout.addWidget(self.h_cols_label, 1, 1, 1, 1)
        self.honeycomb_steps_spin_box = QtWidgets.QSpinBox(self.tab_honeycomb)
        self.honeycomb_steps_spin_box.setMinimum(2)
        self.honeycomb_steps_spin_box.setMaximum(2000)
        self.honeycomb_steps_spin_box.setSingleStep(1)
        self.honeycomb_steps_spin_box.setProperty("value", 2)
        self.honeycomb_steps_spin_box.setObjectName("honeycomb_steps_spin_box")
        self.honeycomb_g_layout.addWidget(self.honeycomb_steps_spin_box, 0, 2, 1, 1)
        self.h_bases_label = QtWidgets.QLabel(self.tab_honeycomb)
        self.h_bases_label.setObjectName("h_bases_label")
        self.honeycomb_g_layout.addWidget(self.h_bases_label, 1, 2, 1, 1)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.honeycomb_g_layout)
        self.vertical_layout_3.addLayout(self.formLayout_3)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/part/dlg_honeycomb"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tab_widget_2.addTab(self.tab_honeycomb, icon4, "")
        self.tab_square = QtWidgets.QWidget()
        self.tab_square.setObjectName("tab_square")
        self.vertical_layout_2 = QtWidgets.QVBoxLayout(self.tab_square)
        self.vertical_layout_2.setObjectName("vertical_layout_2")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.dimensionsLabel2 = QtWidgets.QLabel(self.tab_square)
        self.dimensionsLabel2.setObjectName("dimensionsLabel2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dimensionsLabel2)
        self.square_g_layout = QtWidgets.QGridLayout()
        self.square_g_layout.setContentsMargins(-1, 3, -1, -1)
        self.square_g_layout.setObjectName("square_g_layout")
        self.square_rows_spin_box = QtWidgets.QSpinBox(self.tab_square)
        self.square_rows_spin_box.setMinimum(6)
        self.square_rows_spin_box.setMaximum(200)
        self.square_rows_spin_box.setProperty("value", 30)
        self.square_rows_spin_box.setObjectName("square_rows_spin_box")
        self.square_g_layout.addWidget(self.square_rows_spin_box, 0, 0, 1, 1)
        self.square_cols_spin_box = QtWidgets.QSpinBox(self.tab_square)
        self.square_cols_spin_box.setMinimum(6)
        self.square_cols_spin_box.setMaximum(200)
        self.square_cols_spin_box.setProperty("value", 30)
        self.square_cols_spin_box.setObjectName("square_cols_spin_box")
        self.square_g_layout.addWidget(self.square_cols_spin_box, 0, 1, 1, 1)
        self.s_rows_label = QtWidgets.QLabel(self.tab_square)
        self.s_rows_label.setAlignment(QtCore.Qt.AlignCenter)
        self.s_rows_label.setObjectName("s_rows_label")
        self.square_g_layout.addWidget(self.s_rows_label, 1, 0, 1, 1)
        self.s_cols_label = QtWidgets.QLabel(self.tab_square)
        self.s_cols_label.setAlignment(QtCore.Qt.AlignCenter)
        self.s_cols_label.setObjectName("s_cols_label")
        self.square_g_layout.addWidget(self.s_cols_label, 1, 1, 1, 1)
        self.square_steps_spin_box = QtWidgets.QSpinBox(self.tab_square)
        self.square_steps_spin_box.setMinimum(2)
        self.square_steps_spin_box.setMaximum(2000)
        self.square_steps_spin_box.setObjectName("square_steps_spin_box")
        self.square_g_layout.addWidget(self.square_steps_spin_box, 0, 2, 1, 1)
        self.s_bases_label = QtWidgets.QLabel(self.tab_square)
        self.s_bases_label.setObjectName("s_bases_label")
        self.square_g_layout.addWidget(self.s_bases_label, 1, 2, 1, 1)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.square_g_layout)
        self.vertical_layout_2.addLayout(self.formLayout_2)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/part/dlg_square"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tab_widget_2.addTab(self.tab_square, icon5, "")
        self.verticalLayout.addWidget(self.tab_widget_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.auto_scaf_label = QtWidgets.QLabel(self.parts_tab)
        self.auto_scaf_label.setObjectName("auto_scaf_label")
        self.horizontalLayout.addWidget(self.auto_scaf_label)
        self.auto_scaf_combo_box = QtWidgets.QComboBox(self.parts_tab)
        self.auto_scaf_combo_box.setObjectName("auto_scaf_combo_box")
        self.auto_scaf_combo_box.addItem("")
        self.auto_scaf_combo_box.addItem("")
        self.horizontalLayout.addWidget(self.auto_scaf_combo_box)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tab_widget.addTab(self.parts_tab, "")
        self.plugins_tab = QtWidgets.QWidget()
        self.plugins_tab.setObjectName("plugins_tab")
        self.vertical_layout_5 = QtWidgets.QVBoxLayout(self.plugins_tab)
        self.vertical_layout_5.setObjectName("vertical_layout_5")
        self.plugin_table_widget = QtWidgets.QTableWidget(self.plugins_tab)
        self.plugin_table_widget.setObjectName("plugin_table_widget")
        self.plugin_table_widget.setColumnCount(1)
        self.plugin_table_widget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.plugin_table_widget.setHorizontalHeaderItem(0, item)
        self.plugin_table_widget.horizontalHeader().setStretchLastSection(True)
        self.vertical_layout_5.addWidget(self.plugin_table_widget)
        self.add_plugin_button = QtWidgets.QPushButton(self.plugins_tab)
        self.add_plugin_button.setObjectName("add_plugin_button")
        self.vertical_layout_5.addWidget(self.add_plugin_button)
        self.tab_widget.addTab(self.plugins_tab, "")
        self.vertical_layout.addWidget(self.tab_widget, QtCore.Qt.AlignTop)
        self.actionClose = QtWidgets.QAction(Preferences)
        self.actionClose.setObjectName("actionClose")

        self.retranslateUi(Preferences)
        self.tab_widget.setCurrentIndex(0)
        self.tab_widget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Preferences)

    def retranslateUi(self, Preferences):
        _translate = QtCore.QCoreApplication.translate
        Preferences.setWindowTitle(_translate("Preferences", "Preferences"))
        self.default_tool_label.setText(_translate("Preferences", "Default tool at startup:"))
        self.default_tool_combo_box.setItemText(0, _translate("Preferences", "Select Tool"))
        self.default_tool_combo_box.setItemText(1, _translate("Preferences", "Pencil Tool"))
        self.default_tool_combo_box.setItemText(2, _translate("Preferences", "Paint"))
        self.default_tool_combo_box.setItemText(3, _translate("Preferences", "Add Seq"))
        self.zoom_speed_label.setText(_translate("Preferences", "Mousewheel zoom speed:"))
        self.show_icon_label_text.setText(_translate("Preferences", "Show Icon Labels:"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.interface_tab), _translate("Preferences", "Interface"))
        self.dimensionsLabel1.setText(_translate("Preferences", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Default</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">dimensions</p></body></html>"))
        self.h_rows_label.setText(_translate("Preferences", "rows"))
        self.h_cols_label.setText(_translate("Preferences", "columns"))
        self.h_bases_label.setText(_translate("Preferences", "bases (x21)"))
        self.tab_widget_2.setTabText(self.tab_widget_2.indexOf(self.tab_honeycomb), _translate("Preferences", "Honeycomb"))
        self.dimensionsLabel2.setText(_translate("Preferences", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Default</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">dimensions</p></body></html>"))
        self.s_rows_label.setText(_translate("Preferences", "rows"))
        self.s_cols_label.setText(_translate("Preferences", "columns"))
        self.s_bases_label.setText(_translate("Preferences", "bases (x32)"))
        self.tab_widget_2.setTabText(self.tab_widget_2.indexOf(self.tab_square), _translate("Preferences", "Square"))
        self.auto_scaf_label.setText(_translate("Preferences", "Auto-scaffold style:"))
        self.auto_scaf_combo_box.setItemText(0, _translate("Preferences", "Mid-seam"))
        self.auto_scaf_combo_box.setItemText(1, _translate("Preferences", "Raster"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.parts_tab), _translate("Preferences", "Parts"))
        item = self.plugin_table_widget.horizontalHeaderItem(0)
        item.setText(_translate("Preferences", "Path"))
        self.add_plugin_button.setText(_translate("Preferences", "Add Plugin"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.plugins_tab), _translate("Preferences", "Plugins"))
        self.actionClose.setText(_translate("Preferences", "Close"))
        self.actionClose.setShortcut(_translate("Preferences", "Ctrl+W"))

import cadnano.gui.ui.dialogs.dialogicons_rc as dialogicons_rc
