language: python
sudo: false

matrix:
  include:
    - python: 3.5
      env:
        - PYQT_VERSION=5.7.1

    - python: 3.5
      env:
        - PYQT_VERSION=5.8

    - python: 3.6
      env:
        - PYQT_VERSION=5.7.1

    - python: 3.6
      env:
        - PYQT_VERSION=5.8

# Command to install dependencies
install:
    - pip install PyQt5==$PYQT_VERSION PyQt3D==$PYQT_VERSION numpy pandas
    - python setup.py install

# Command to run tests
script: pytest cadnano/tests
