from PyQt5.QtGui import QFont
from cadnano.gui.views.styles import THE_FONT, THE_FONT_SIZE
from cadnano.gui.views.styles import BLUE_FILL, BLUE_STROKE
from cadnano.gui.views.styles import GRAY_FILL, GRAY_STROKE


# Slice Sizing
SLICE_HELIX_RADIUS = 15.
SLICE_HELIX_STROKE_WIDTH = 0.5
SLICE_HELIX_MOD_HILIGHT_WIDTH = 1

# Z values
# bottom
ZSLICEHELIX = 40
ZSELECTION = 50
ZDESELECTOR = 60
ZWEDGEGIZMO = 100
ZPXIGROUP = 150
ZPARTITEM = 200
# top

# Part apperance
SLICE_FILL = "#ffffff"

DEFAULT_PEN_WIDTH = 1
DEFAULT_ALPHA = 2
SELECTED_COLOR = '#5a8bff'
SELECTED_PEN_WIDTH = 2
SELECTED_ALPHA = 0


SLICE_NUM_FONT = QFont(THE_FONT, 10, QFont.Bold)
USE_TEXT_COLOR = "#ffffff"
SLICE_TEXT_COLOR = "#000000"

ACTIVE_STROKE = '#cccc00'
DEFAULT_GRID_DOT_COLOR = '#0000ff'
ACTIVE_GRID_DOT_COLOR = '#ff3333'  # item color
